language: python
dist: trusty
python:
  - "3.5"
install:
  - apt-get install libc6
  - pip install -r requirements.txt
  - pip install coveralls cov-core
script: nose2 --with-coverage
after_success: coveralls
