language: python
sudo: required
dist: trusty
python:
  - "3.5"
install:
  - sudo apt-get install libc6
  - pip install -r requirements.txt
  - pip install coveralls cov-core
script: nose2 --with-coverage
after_success: coveralls
branches:
  only:
    - master
    - develop
